---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration
  hosts: bigmike
  vars_files:
    - vars/main.yml
    - vars/parameters.yml
  roles:
    - { name: basic, become: true, tags: basic}
    - { name: mariadb, become: true, tags: mariadb }
    - { name: powerdns, become: true, tags: powerdns }
    - { name: letsencrypt, become: true, tags: letsencrypt }
    - { name: letsencrypt, become: true, tags: letsencrypt, server_domain: torrent.bigmike.ovh }
    - { name: proftpd, become: true, tags: proftpd }
    - { name: nginx, become: true, tags: nginx }
    - { name: pma, become: true, tags: pma }
    - { name: varnish, become: true, tags: varnish }
    - { name: postfix, become: true, tags: postfix }
    - { name: phpfarm, become: true, tags: phpfarm }
    - { name: firewall, become: true, tags: firewall }
    - { name: fail2ban, become: true, tags: fail2ban }
    - { name: logwatch, become: true, tags: logwatch }
    - { name: secure, become: true, tags: secure }
    - { name: monit, become: true, tags: monit }
    - { name: munin, become: true, tags: munin }
    - { name: backup, become: true, tags: backup }
    - { name: jasonroyle.rabbitmq, become: true, tags: rabbitmq }