- name: Install logwatch
  apt: name=logwatch state=installed

- name: Email log summary daily
  lineinfile:
    dest: /etc/cron.daily/00logwatch
    regexp: '^/usr/sbin/logwatch'
    line: '/usr/sbin/logwatch --output mail --mailto {{ admin1_mail }},{{ admin2_mail }} --detail high'
    state: present
    create: yes

- name: Change file mode
  file: path=/etc/cron.daily/00logwatch mode=755