- apt: name="{{item}}" state=installed
  with_items:
  - ncftp
  - mailutils
  - unattended-upgrades
  - ntp
  - daemon
  - ntpdate
  - sudo
  - curl
  - redis-server
  - memcached
  - openssl
  - mcrypt
  - arj
  - cabextract
  - lzop
  - nomarch
  - p7zip-full
  - ripole
  - rpm2cpio
  - tnef
  - unzip
  - unrar-free
  - zip
  - zoo
  - bzip2
  - dnsutils
  - imagemagick
  - binutils
  - make
  - wget
  - gcc
  - autoconf
  - tar
  - bzip2
  - libxml2-dev
  - libjpeg-turbo8-dev
  - libpng-dev
  - libicu-dev
  - libmcrypt-dev
  - librabbitmq-dev
  - pkg-config
  - libc-client-dev
  - libcurl4-openssl-dev
  - libssl-dev
  - libkrb5-dev
  - libbz2-dev
  - libxslt-dev
  - libmagickwand-dev
  - libbison-dev
  - python-pip
  - python-dev
  - libffi-dev
  - libxslt1-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libcache-perl
  - libcache-cache-perl