- name: Install fail2ban
  apt: name=fail2ban state=installed

- name: copy fail2ban config
  template:
    src: config.j2
    dest: "/etc/fail2ban/jail.d/config.conf"
  notify: restart fail2ban

- meta: flush_handlers