- name: Install munin
  apt: name=munin state=installed

- name: Install munin-node
  apt: name=munin-node state=installed

- name: Install munin plugins
  apt: name=munin-plugins-extra state=installed

- name: Install spawn-fcgi
  apt: name=spawn-fcgi state=installed

- name: "Install munin-cgi-graph.service"
  template:
    src: munin-cgi-graph.service.j2
    dest: "/etc/systemd/system/munin-cgi-graph.service"
    mode: 0664
  notify:
    - "reload systemd"
    - "start munin-cgi"

- name: "Install munin-cgi-html.service"
  template:
    src: munin-cgi-html.service.j2
    dest: "/etc/systemd/system/munin-cgi-html.service"
    mode: 0664
  notify:
    - "reload systemd"
    - "start munin-cgi"

- meta: flush_handlers