- name: Create munin user
  mysql_user: login_user=root login_password={{ mysql_root_password }} name=munin password=munin priv="*.*:PROCESS,REPLICATION CLIENT" state=present

- name: Is new mysql_ plugin
  shell: "cat /usr/share/munin/plugins/mysql_ | grep 'MariaDB 10.0' | wc -l"
  register: new_mysql_plugin
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- file: path=/usr/share/munin/plugins/mysql_ state=absent
  when: new_mysql_plugin.stdout == '0'

- name: download newer mysql_ plugin
  get_url:
    url: https://raw.githubusercontent.com/munin-monitoring/munin/master/plugins/node.d/mysql_
    dest: /usr/share/munin/plugins/mysql_
    mode: 0755

- meta: flush_handlers

- name: Install CpanM
  apt: name=cpanminus state=installed

- name: Install cache plugin
  apt: name=libcache-perl state=installed

- name: Install cache plugin2
  apt: name=libcache-cache-perl state=installed


- name: Install Dependencies for munin
  cpanm:
    name: "{{ item }}"
    system_lib: yes
  with_items:
    - Cache::Cache
    - DBD::mysql

- name: munin mysql config
  template: src=mysql.munin.j2 dest=/etc/munin/plugin-conf.d/mysql_
  notify: reload munin

# must be flushed prior suggesting
- meta: flush_handlers

- shell: "munin-node-configure --shell"
  changed_when: False
  check_mode: no
  failed_when: false

- shell: "munin-node-configure --shell > /dev/null 2>&1 ; /usr/share/munin/plugins/mysql_ suggest"
  register: munin_scripts
  changed_when: False
  check_mode: no

- name: "Install mysql munin scripts"
  file:
    src: "/usr/share/munin/plugins/mysql_"
    dest: "/etc/munin/plugins/mysql_{{ item }}"
    state: link
  with_items: "{{ munin_scripts.stdout_lines }}"
  notify: reload munin