- find:
    paths: "/usr/share/munin/plugins/php5-fpm-munin-plugins"
    patterns: "phpfpm_*"
  register: munin_files

- file:
    src: "{{ item.path }}"
    dest: "/etc/munin/plugins/{{ item.path|basename }}"
    state: link
  with_items: "{{ munin_files.files }}"
