- name: Install letsencrypt
  apt: name=letsencrypt state=installed

- stat: path="/etc/letsencrypt/live/{{ server_domain }}/fullchain.pem"
  register: letsencrypt_cert

- name: Check if nginx is installed
  command: "dpkg -s nginx"
  register: nginx_check
  ignore_errors: yes
  failed_when: false
  changed_when: false

- name: stop nginx
  service: name=nginx state=stopped
  when: letsencrypt_cert.stat.exists == False and nginx_check.stdout.find('install ok installed') != -1

- name: Generate letsencrypt certificate
  shell: "letsencrypt certonly --standalone --agree-tos --email=admin@{{ server_domain }} -d {{ server_domain }} -d www.{{ server_domain }} -d mail.{{ server_domain }} --text"
  args:
    creates: "/etc/letsencrypt/live/{{ server_domain }}/fullchain.pem"
  when: letsencrypt_cert.stat.exists == False

- name: start nginx
  service: name=nginx state=started
  when: nginx_check.stdout.find('install ok installed') != -1